### ISSUE TITLE
Unable to match command output after in v.1.12.0

### ISSUE THREAD

**Issue by p-linnane** [cloudentity/oauth2c#80]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v1.12.0 of oauth2c, we are encountering a test failure matching the "Authorization completed" output. It appears this was changed in https://github.com/cloudentity/oauth2c/pull/77. Our test is not just receiving the access token response instead of the full output. Is there any way to resolve this? Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/147883

**Comment by mbilski** [comment]
Hi @p-linnane 

Could you change the assertion to look for `access_token` instead of `Authorization completed` in line 28?

In #77 I moved all the diagnostic output to the stderr so it is possible to use it in scripts as requested in #76.

That's why the testing is failing now, as it expects the `Authorization completed` in stdout, not stderr.

**Comment by p-linnane** [comment]
Thank you. I've made that change and the test is passing now.
